/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sventas.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuarios1
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    Clientes clientes;//Creamos un objeto con nombre clientes de la clase Clientes (No vamos a instanciarlo de momento)
    Productos productos;
    RegistrarVentas ventas;
    Proveedores proveedores;
    ConsultarVentas consultarVentas;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_cliente = new javax.swing.JButton();
        jb_registratProducto = new javax.swing.JButton();
        jb_proveedor = new javax.swing.JButton();
        jb_registrarVentas = new javax.swing.JButton();
        bt_consultarVentas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_opciones = new javax.swing.JMenu();
        mnu_sobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnu_salir = new javax.swing.JMenuItem();
        mn_registros = new javax.swing.JMenu();
        mnu_cliente = new javax.swing.JMenuItem();
        mnu_producto = new javax.swing.JMenuItem();
        mnu_proveedor = new javax.swing.JMenuItem();
        mn_ventas = new javax.swing.JMenu();
        mnu_regVenta = new javax.swing.JMenuItem();
        mn_consultarVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");

        jb_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/sventas/view/imagen/clientes.gif"))); // NOI18N
        jb_cliente.setText("Cliente");
        jb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clienteActionPerformed(evt);
            }
        });

        jb_registratProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/sventas/view/imagen/productos.gif"))); // NOI18N
        jb_registratProducto.setText("Producto");
        jb_registratProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registratProductoActionPerformed(evt);
            }
        });

        jb_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/sventas/view/imagen/proveedor.gif"))); // NOI18N
        jb_proveedor.setText("Proveedor");
        jb_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_proveedorActionPerformed(evt);
            }
        });

        jb_registrarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/sventas/view/imagen/ventas.gif"))); // NOI18N
        jb_registrarVentas.setText("Registrar Ventas");
        jb_registrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarVentasActionPerformed(evt);
            }
        });

        bt_consultarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/sventas/view/imagen/ventas.gif"))); // NOI18N
        bt_consultarVentas.setText("Consultar Ventas");
        bt_consultarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consultarVentasActionPerformed(evt);
            }
        });

        mn_opciones.setText("Opciones");

        mnu_sobre.setText("Sobre el sistema");
        mnu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_sobreActionPerformed(evt);
            }
        });
        mn_opciones.add(mnu_sobre);
        mn_opciones.add(jSeparator1);

        mnu_salir.setText("Salir");
        mnu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_salirActionPerformed(evt);
            }
        });
        mn_opciones.add(mnu_salir);

        jMenuBar1.add(mn_opciones);

        mn_registros.setText("Registros");

        mnu_cliente.setText("Cliente");
        mnu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_clienteActionPerformed(evt);
            }
        });
        mn_registros.add(mnu_cliente);

        mnu_producto.setText("Producto");
        mnu_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_productoActionPerformed(evt);
            }
        });
        mn_registros.add(mnu_producto);

        mnu_proveedor.setText("Proveedor");
        mnu_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_proveedorActionPerformed(evt);
            }
        });
        mn_registros.add(mnu_proveedor);

        jMenuBar1.add(mn_registros);

        mn_ventas.setText("Ventas");

        mnu_regVenta.setText("Registrar ventas");
        mnu_regVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_regVentaActionPerformed(evt);
            }
        });
        mn_ventas.add(mnu_regVenta);

        mn_consultarVentas.setText("Consultar ventas");
        mn_consultarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultarVentasActionPerformed(evt);
            }
        });
        mn_ventas.add(mn_consultarVentas);

        jMenuBar1.add(mn_ventas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_consultarVentas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_registratProducto)
                            .addComponent(jb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_proveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_registrarVentas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(63, 63, 63))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_consultarVentas, jb_cliente, jb_proveedor, jb_registrarVentas, jb_registratProducto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_proveedor))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_registratProducto)
                    .addComponent(jb_registrarVentas))
                .addGap(37, 37, 37)
                .addComponent(bt_consultarVentas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_consultarVentas, jb_cliente, jb_proveedor, jb_registrarVentas, jb_registratProducto});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_sobreActionPerformed
       JOptionPane.showMessageDialog(null, "Sistema de Ventas");
    }//GEN-LAST:event_mnu_sobreActionPerformed

    private void salir()
    {
        System.exit(0);//EL metodo exit de la clase System cierra la aplicación y el parametro 0 indica el sistema que esta
        //terminando en forma normal
    }
    
    private void mnu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_salirActionPerformed
        salir();// Cuando nosotros hacemos clic en el menu Salir, el ejecuta el metodo y llama al metodo salir
        
    }//GEN-LAST:event_mnu_salirActionPerformed
    private void mostrarCliente()
    {
        if (clientes ==null)
        {
            clientes = new Clientes();
            clientes.setVisible(true);
        }
        else
        {
            clientes.setVisible(true);
            clientes.setState(JFrame.NORMAL);
        }
    }
    private void mnu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_clienteActionPerformed
        mostrarCliente();
    }//GEN-LAST:event_mnu_clienteActionPerformed

    private void jb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clienteActionPerformed
        mostrarCliente();
    }//GEN-LAST:event_jb_clienteActionPerformed
private void mostrarProducto()
    {
        if (productos ==null)
        {
            productos = new Productos();
            productos.setVisible(true);
        }
        else
        {
            productos.setVisible(true);
            productos.setState(JFrame.NORMAL);
        }
    }
    private void mnu_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_productoActionPerformed
        mostrarProducto();
    }//GEN-LAST:event_mnu_productoActionPerformed

    private void jb_registratProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registratProductoActionPerformed
        mostrarProducto();
    }//GEN-LAST:event_jb_registratProductoActionPerformed
private void mostrarProveedor()
    {
        if (proveedores ==null)
        {
            proveedores = new Proveedores();
            proveedores.setVisible(true);
        }
        else
        {
            proveedores.setVisible(true);
            proveedores.setState(JFrame.NORMAL);
        }
    }
    private void mnu_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_proveedorActionPerformed
        mostrarProveedor();
    }//GEN-LAST:event_mnu_proveedorActionPerformed

    private void jb_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_proveedorActionPerformed
        mostrarProveedor();
    }//GEN-LAST:event_jb_proveedorActionPerformed
private void mostrarConsultaVentas()
    {
        if (consultarVentas ==null)
        {
            consultarVentas = new ConsultarVentas();
            consultarVentas.setVisible(true);
        }
        else
        {
            consultarVentas.setVisible(true);
            consultarVentas.setState(JFrame.NORMAL);
        }
    }
    private void mn_consultarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultarVentasActionPerformed
        mostrarConsultaVentas();
    }//GEN-LAST:event_mn_consultarVentasActionPerformed

    private void jb_registrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarVentasActionPerformed
        mostrarVenta();
    }//GEN-LAST:event_jb_registrarVentasActionPerformed

    private void mostrarVenta()
    {
        if (ventas ==null)
        {
            ventas = new RegistrarVentas();
            ventas.setVisible(true);
        }
        else
        {
            ventas.setVisible(true);
            ventas.setState(JFrame.NORMAL);
        }
    }
    private void mnu_regVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_regVentaActionPerformed
        mostrarVenta();
    }//GEN-LAST:event_mnu_regVentaActionPerformed

    private void bt_consultarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consultarVentasActionPerformed
        mostrarConsultaVentas();
    }//GEN-LAST:event_bt_consultarVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_consultarVentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jb_cliente;
    private javax.swing.JButton jb_proveedor;
    private javax.swing.JButton jb_registrarVentas;
    private javax.swing.JButton jb_registratProducto;
    private javax.swing.JMenuItem mn_consultarVentas;
    private javax.swing.JMenu mn_opciones;
    private javax.swing.JMenu mn_registros;
    private javax.swing.JMenu mn_ventas;
    private javax.swing.JMenuItem mnu_cliente;
    private javax.swing.JMenuItem mnu_producto;
    private javax.swing.JMenuItem mnu_proveedor;
    private javax.swing.JMenuItem mnu_regVenta;
    private javax.swing.JMenuItem mnu_salir;
    private javax.swing.JMenuItem mnu_sobre;
    // End of variables declaration//GEN-END:variables
}
